// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIjId_x7fGXIOVBXJ9DNLeF-RpIIhQ9qo',
    appId: '1:377320402777:web:44e48cf34d4f36d2922648',
    messagingSenderId: '377320402777',
    projectId: 'complaint-management-module',
    authDomain: 'complaint-management-module.firebaseapp.com',
    storageBucket: 'complaint-management-module.firebasestorage.app',
    measurementId: 'G-HT7EBZT6HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4JTKD7gGsKO7MuL6XvCFuwNOGd49R-e4',
    appId: '1:377320402777:android:743dc268351e41d4922648',
    messagingSenderId: '377320402777',
    projectId: 'complaint-management-module',
    storageBucket: 'complaint-management-module.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJpOEQY9EXimqYlN5M0olOagBDII9xnlI',
    appId: '1:377320402777:ios:3684b90f2ec36bc2922648',
    messagingSenderId: '377320402777',
    projectId: 'complaint-management-module',
    storageBucket: 'complaint-management-module.firebasestorage.app',
    iosBundleId: 'com.example.complaintManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIjId_x7fGXIOVBXJ9DNLeF-RpIIhQ9qo',
    appId: '1:377320402777:web:44e48cf34d4f36d2922648',
    messagingSenderId: '377320402777',
    projectId: 'complaint-management-module',
    authDomain: 'complaint-management-module.firebaseapp.com',
    storageBucket: 'complaint-management-module.firebasestorage.app',
    measurementId: 'G-HT7EBZT6HG',
  );
}
